In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset("diamonds")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [3]:
## chehcking null values
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [4]:
### seprating data as x and y
y = df[["price"]]
x = df.drop(labels="price",axis=1)

In [5]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
dtypes: category(3), float64(6)
memory usage: 2.6 MB

In [6]:
x_num = x.select_dtypes(include="float64")
x_num.head()

   carat  depth  table     x     y     z
0   0.23   61.5   55.0  3.95  3.98  2.43
1   0.21   59.8   61.0  3.89  3.84  2.31
2   0.23   56.9   65.0  4.05  4.07  2.31
3   0.29   62.4   58.0  4.20  4.23  2.63
4   0.31   63.3   58.0  4.34  4.35  2.75

In [ ]:
x_char = x.select_dtypes(exclude="float64")
from sklearn.preprocessing import LabelEncoder
import pickle

# Make independent copy
x_char = x.select_dtypes(exclude="float64").copy()

# Encode categorical columns ONCE
cut_le = LabelEncoder()
x_char["cut"] = cut_le.fit_transform(x_char["cut"])

color_le = LabelEncoder()
x_char["color"] = color_le.fit_transform(x_char["color"])

clarity_le = LabelEncoder()
x_char["clarity"] = clarity_le.fit_transform(x_char["clarity"])

# Save the encoders
with open("cut_le.pkl", "wb") as f:
    pickle.dump(cut_le, f)

with open("color_le.pkl", "wb") as f:
    pickle.dump(color_le, f)

with open("clarity_le.pkl", "wb") as f:
    pickle.dump(clarity_le, f)

# Check
print("CUT:", cut_le.classes_)
print("COLOR:", color_le.classes_)
print("CLARITY:", clarity_le.classes_)

BEFORE ENCODING:
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']
['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']

       cut color clarity
0    Ideal     E     SI2
1  Premium     E     SI1
2     Good     E     VS1
3  Premium     I     VS2
4     Good     J     SI2

In [ ]:

pickle.dump(cut_le, open("cut_le.pkl", "wb"))
pickle.dump(color_le, open("color_le.pkl", "wb"))
pickle.dump(clarity_le, open("clarity_le.pkl", "wb"))

JUST BEFORE LABEL ENCODER:
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']
['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [16]:
x_scaling = pd.DataFrame(sc.fit_transform(x_num),
                         columns = x_num.columns,
                         index=x_num.index)
x_scaling.head()

      carat     depth     table         x         y         z
0 -1.198168 -0.174092 -1.099672 -1.587837 -1.536196 -1.571129
1 -1.240361 -1.360738  1.585529 -1.641325 -1.658774 -1.741175
2 -1.198168 -3.385019  3.375663 -1.498691 -1.457395 -1.741175
3 -1.071587  0.454133  0.242928 -1.364971 -1.317305 -1.287720
4 -1.029394  1.082358  0.242928 -1.240167 -1.212238 -1.117674

In [12]:
data = pd.concat([x_char,x_scaling],axis=1)
data.head()

,cut,color,clarity,carat,depth,table,x,y,z
0,2,1,3,-1.198168,-0.174092,-1.099672,-1.587837,-1.536196,-1.571129
1,3,1,2,-1.240361,-1.360738,1.585529,-1.641325,-1.658774,-1.741175
2,1,1,4,-1.198168,-3.385019,3.375663,-1.498691,-1.457395,-1.741175
3,3,5,5,-1.071587,0.454133,0.242928,-1.364971,-1.317305,-1.287720
4,1,6,3,-1.029394,1.082358,0.242928,-1.240167,-1.212238,-1.117674

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,y,
                                                test_size=0.2,
                                                random_state=45)

In [17]:
from sklearn.neighbors import KNeighborsRegressor
knn =KNeighborsRegressor(n_neighbors=4)

In [18]:
knn.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=4)

In [19]:
ypred=knn.predict(x_test)
from sklearn.metrics import r2_score
print(r2_score(y_test,ypred))

0.9624614914939442

In [20]:
pickle.dump(knn,open("diamond_knn.pkl","wb"))
pickle.dump(sc,open("diamond_scaling.pkl","wb"))

In [ ]:
cut color clarity x y z depth ->button(predict)